version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minion
    ports:
      - "9000:9000" # API (para upload/download via código)
      - "9001:9001" # Console web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
