version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: anime-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass dev123456
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=dev123456
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  redis_data:
    driver: local
