[project]
name = "whats-episode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "imagehash>=4.3.2",
    "opencv-python>=4.11.0.86",
    "pillow>=11.2.1",
]
